#!/bin/bash

lsc -c index.ls
#markdown index.markdown > content.html
marked index.markdown > content.html
cat header.html content.html jqueryscript.html scriptopen.html index.js scriptclose.html footer.html > index.html
#git commit -a -m "updated main page"
